#![forbid(unsafe_code)]

use crate::McpServer;
use serde_json::Value;

pub(crate) fn dispatch_branchmind_tool(
    server: &mut McpServer,
    name: &str,
    args: Value,
) -> Option<Value> {
    let resp = match name {
        "init" => server.tool_branchmind_init(args),
        "status" => server.tool_branchmind_status(args),
        "workspace_use" => server.tool_branchmind_workspace_use(args),
        "workspace_reset" => server.tool_branchmind_workspace_reset(args),
        "open" => server.tool_branchmind_open(args),
        "help" => server.tool_branchmind_help(args),
        "skill" => server.tool_branchmind_skill(args),
        "diagnostics" => server.tool_branchmind_diagnostics(args),
        "anchors_list" => server.tool_branchmind_anchors_list(args),
        "anchor_snapshot" => server.tool_branchmind_anchor_snapshot(args),
        "macro_anchor_note" => server.tool_branchmind_macro_anchor_note(args),
        "anchors_export" => server.tool_branchmind_anchors_export(args),
        "anchors_rename" => server.tool_branchmind_anchors_rename(args),
        "anchors_bootstrap" => server.tool_branchmind_anchors_bootstrap(args),
        "anchors_merge" => server.tool_branchmind_anchors_merge(args),
        "anchors_lint" => server.tool_branchmind_anchors_lint(args),
        "branch_create" => server.tool_branchmind_branch_create(args),
        "macro_branch_note" => server.tool_branchmind_macro_branch_note(args),
        "branch_list" => server.tool_branchmind_branch_list(args),
        "checkout" => server.tool_branchmind_checkout(args),
        "branch_rename" => server.tool_branchmind_branch_rename(args),
        "branch_delete" => server.tool_branchmind_branch_delete(args),
        "notes_commit" => server.tool_branchmind_notes_commit(args),
        "commit" => server.tool_branchmind_commit(args),
        "log" => server.tool_branchmind_log(args),
        "docs_list" => server.tool_branchmind_docs_list(args),
        "knowledge_list" => server.tool_branchmind_knowledge_list(args),
        "tag_create" => server.tool_branchmind_tag_create(args),
        "tag_list" => server.tool_branchmind_tag_list(args),
        "tag_delete" => server.tool_branchmind_tag_delete(args),
        "reflog" => server.tool_branchmind_reflog(args),
        "reset" => server.tool_branchmind_reset(args),
        "show" => server.tool_branchmind_show(args),
        "diff" => server.tool_branchmind_diff(args),
        "merge" => server.tool_branchmind_merge(args),
        "graph_apply" => server.tool_branchmind_graph_apply(args),
        "graph_query" => server.tool_branchmind_graph_query(args),
        "graph_validate" => server.tool_branchmind_graph_validate(args),
        "graph_diff" => server.tool_branchmind_graph_diff(args),
        "graph_merge" => server.tool_branchmind_graph_merge(args),
        "graph_conflicts" => server.tool_branchmind_graph_conflicts(args),
        "graph_conflict_show" => server.tool_branchmind_graph_conflict_show(args),
        "graph_conflict_resolve" => server.tool_branchmind_graph_conflict_resolve(args),
        "think_template" => server.tool_branchmind_think_template(args),
        "think_card" => server.tool_branchmind_think_card(args),
        "think_add_hypothesis" => server.tool_branchmind_think_add_hypothesis(args),
        "think_add_question" => server.tool_branchmind_think_add_question(args),
        "think_add_test" => server.tool_branchmind_think_add_test(args),
        "think_add_note" => server.tool_branchmind_think_add_note(args),
        "think_add_decision" => server.tool_branchmind_think_add_decision(args),
        "think_add_evidence" => server.tool_branchmind_think_add_evidence(args),
        "think_add_knowledge" => server.tool_branchmind_think_add_knowledge(args),
        "think_add_frame" => server.tool_branchmind_think_add_frame(args),
        "think_add_update" => server.tool_branchmind_think_add_update(args),
        "think_context" => server.tool_branchmind_think_context(args),
        "think_pipeline" => server.tool_branchmind_think_pipeline(args),
        "think_query" => server.tool_branchmind_think_query(args),
        "think_pack" => server.tool_branchmind_think_pack(args),
        "think_frontier" => server.tool_branchmind_think_frontier(args),
        "think_next" => server.tool_branchmind_think_next(args),
        "think_link" => server.tool_branchmind_think_link(args),
        "think_set_status" => server.tool_branchmind_think_set_status(args),
        "think_pin" => server.tool_branchmind_think_pin(args),
        "think_pins" => server.tool_branchmind_think_pins(args),
        "think_publish" => server.tool_branchmind_think_publish(args),
        "think_nominal_merge" => server.tool_branchmind_think_nominal_merge(args),
        "think_playbook" => server.tool_branchmind_think_playbook(args),
        "think_subgoal_open" => server.tool_branchmind_think_subgoal_open(args),
        "think_subgoal_close" => server.tool_branchmind_think_subgoal_close(args),
        "think_watch" => server.tool_branchmind_think_watch(args),
        "think_lint" => server.tool_branchmind_think_lint(args),
        "trace_step" => server.tool_branchmind_trace_step(args),
        "trace_sequential_step" => server.tool_branchmind_trace_sequential_step(args),
        "trace_hydrate" => server.tool_branchmind_trace_hydrate(args),
        "trace_validate" => server.tool_branchmind_trace_validate(args),
        "context_pack" => server.tool_branchmind_context_pack(args),
        "context_pack_export" => server.tool_branchmind_context_pack_export(args),
        "export" => server.tool_branchmind_export(args),
        "transcripts_search" => server.tool_branchmind_transcripts_search(args),
        "transcripts_open" => server.tool_branchmind_transcripts_open(args),
        "transcripts_digest" => server.tool_branchmind_transcripts_digest(args),
        _ => return None,
    };
    Some(resp)
}
